# Generated by Django 3.2.2 on 2021-05-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchimg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sekil',
            name='image',
            field=models.ImageField(upload_to='uploaded/'),
        ),
    ]
